# Site settings
title: Kevin Dong
email: dongk@live.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/home/" 
url: "https://dongkevin.github.io/umbrella"

twitter_username: dongkevin
github_username: dongkevin

# Build settings
markdown: kramdown
